/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaNanoSerenade;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author aliay
 */
public class ManageBibliographyForm extends javax.swing.JFrame {

    
    BIBLIOGRAPHY bibliography = new BIBLIOGRAPHY();
    
    /**
     * Creates new form ManageRoomsForm
     */
    public ManageBibliographyForm() {
        initComponents();
        
//        //avoir une fenetre à la taille de l'écran
//        Dimension dimension = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
//        int height = (int)dimension.getHeight();
//        int width  = (int)dimension.getWidth();
//        System.out.println(height);
//        System.out.println(width);
//        Dimension d= new Dimension(height, width);
//        this.setMinimumSize(d);
//        this.setPreferredSize(d);
GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
 
                if( device.isFullScreenSupported() && !this.isDisplayable() ) {
                    this.setUndecorated(true);
                    device.setFullScreenWindow(this); 
                }else {
                    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
                    this.setResizable(true); // on empêche de redimensionner la fenêtre 
                }
        
         //ajout d une icone serende pour la page
          this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/lloogg_ser.png")).getImage());
        
         //populate the jtable
        bibliography.fillBibliographyJTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldPeopleID = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldIDOI = new javax.swing.JTextField();
        jTextFieldInstitutionID = new javax.swing.JTextField();
        jTextFieldBibliographyID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jButtonClearBibliography = new javax.swing.JButton();
        jButtonEditBibliography = new javax.swing.JButton();
        jButtonRemoveBibliography = new javax.swing.JButton();
        jButtonAddBibliography = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMesocosms = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPublications = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemInstitutions = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItemBibliograpgy = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPeople = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItemProtocols = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItemInstruments = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMeasurements = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItemDescription = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItemDictionary = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemDiscover = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItemHelp = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAbout = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Bibliography");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Bibliography informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("People ID:");

        jTextFieldPeopleID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldPeopleID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPeopleIDActionPerformed(evt);
            }
        });

        jLabel57.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Institution ID:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setText("DOI:");

        jTextFieldIDOI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldInstitutionID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldInstitutionID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInstitutionIDActionPerformed(evt);
            }
        });

        jTextFieldBibliographyID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldBibliographyID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldBibliographyIDActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("Bibliography ID:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel57)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel58)
                .addGap(45, 45, 45)
                .addComponent(jLabel52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldBibliographyID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldPeopleID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldInstitutionID, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldIDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldBibliographyID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPeopleID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldInstitutionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldIDOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jLabel58)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bibliography ID", "People ID", "Institution ID", "DOI"
            }
        )
        //make the jtable cell not editable
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTable1.setGridColor(new java.awt.Color(204, 255, 0));

    jTable1.setSelectionBackground(new java.awt.Color(0, 153, 0));

    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jButtonBack.setBackground(new java.awt.Color(204, 204, 204));
    jButtonBack.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/back_button.png"))); // NOI18N
    jButtonBack.setToolTipText("Click to return to the main window.");
    jButtonBack.setBorderPainted(false);
    jButtonBack.setContentAreaFilled(false);
    jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonBack.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonBackActionPerformed(evt);
        }
    });

    jButtonClearBibliography.setBackground(new java.awt.Color(204, 204, 204));
    jButtonClearBibliography.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonClearBibliography.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/reset_button.png"))); // NOI18N
    jButtonClearBibliography.setToolTipText("Click to clear the fields.");
    jButtonClearBibliography.setBorderPainted(false);
    jButtonClearBibliography.setContentAreaFilled(false);
    jButtonClearBibliography.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonClearBibliography.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonClearBibliographyActionPerformed(evt);
        }
    });

    jButtonEditBibliography.setBackground(new java.awt.Color(204, 204, 204));
    jButtonEditBibliography.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonEditBibliography.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/edit_button.png"))); // NOI18N
    jButtonEditBibliography.setToolTipText("Click to edit the details of the selected bibliography.");
    jButtonEditBibliography.setBorderPainted(false);
    jButtonEditBibliography.setContentAreaFilled(false);
    jButtonEditBibliography.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonEditBibliography.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonEditBibliographyActionPerformed(evt);
        }
    });

    jButtonRemoveBibliography.setBackground(new java.awt.Color(204, 204, 204));
    jButtonRemoveBibliography.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonRemoveBibliography.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/remove_button.png"))); // NOI18N
    jButtonRemoveBibliography.setToolTipText("Click to delete the selected bibliography.");
    jButtonRemoveBibliography.setBorderPainted(false);
    jButtonRemoveBibliography.setContentAreaFilled(false);
    jButtonRemoveBibliography.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRemoveBibliography.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRemoveBibliographyActionPerformed(evt);
        }
    });

    jButtonAddBibliography.setBackground(new java.awt.Color(204, 204, 204));
    jButtonAddBibliography.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonAddBibliography.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/save_button.png"))); // NOI18N
    jButtonAddBibliography.setToolTipText("Click to add a new bibliography.");
    jButtonAddBibliography.setBorderPainted(false);
    jButtonAddBibliography.setContentAreaFilled(false);
    jButtonAddBibliography.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonAddBibliography.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAddBibliographyActionPerformed(evt);
        }
    });

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/exit_button.png"))); // NOI18N
    jButton1.setToolTipText("Click to close the application.");
    jButton1.setBorderPainted(false);
    jButton1.setContentAreaFilled(false);
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(70, 70, 70)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1168, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(79, 79, 79)
            .addComponent(jButtonAddBibliography, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(75, 75, 75)
            .addComponent(jButtonEditBibliography, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(75, 75, 75)
            .addComponent(jButtonRemoveBibliography, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(75, 75, 75)
            .addComponent(jButtonClearBibliography, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(75, 75, 75)
            .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 75, Short.MAX_VALUE)
            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(66, 66, 66))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButtonBack, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jButtonClearBibliography, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonAddBibliography)
                .addComponent(jButtonEditBibliography, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jButtonRemoveBibliography, javax.swing.GroupLayout.Alignment.TRAILING)
                .addComponent(jButton1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(80, Short.MAX_VALUE))
    );

    jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jMenuBar1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N

    jMenu5.setText("File ");

    jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem3.setText("Properties");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem3ActionPerformed(evt);
        }
    });
    jMenu5.add(jMenuItem3);
    jMenu5.add(jSeparator4);

    jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem6.setText("Exit");
    jMenuItem6.setToolTipText("Click to close the application.");
    jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem6ActionPerformed(evt);
        }
    });
    jMenu5.add(jMenuItem6);

    jMenuBar1.add(jMenu5);

    jMenu1.setText("Edit >");
    jMenu1.add(jSeparator1);

    jMenuItemMesocosms.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemMesocosms.setText("Mesocosms");
    jMenuItemMesocosms.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemMesocosmsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemMesocosms);
    jMenu1.add(jSeparator2);

    jMenuItemPublications.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemPublications.setText("Publications");
    jMenuItemPublications.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemPublicationsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemPublications);
    jMenu1.add(jSeparator6);

    jMenuItemInstitutions.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemInstitutions.setText("Instutitions");
    jMenuItemInstitutions.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemInstitutionsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemInstitutions);
    jMenu1.add(jSeparator7);

    jMenuItemBibliograpgy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemBibliograpgy.setText("Bibliograpgy");
    jMenuItemBibliograpgy.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemBibliograpgyActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemBibliograpgy);
    jMenu1.add(jSeparator8);

    jMenuItemPeople.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemPeople.setText("People");
    jMenuItemPeople.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemPeopleActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemPeople);
    jMenu1.add(jSeparator9);

    jMenuItemProtocols.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemProtocols.setText("Protocols");
    jMenuItemProtocols.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemProtocolsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemProtocols);
    jMenu1.add(jSeparator10);

    jMenuItemInstruments.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemInstruments.setText("Instruments");
    jMenuItemInstruments.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemInstrumentsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemInstruments);
    jMenu1.add(jSeparator11);

    jMenuItemMeasurements.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemMeasurements.setText("Measurements");
    jMenuItemMeasurements.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemMeasurementsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemMeasurements);
    jMenu1.add(jSeparator12);

    jMenuItemDescription.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemDescription.setText("Description");
    jMenuItemDescription.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemDescriptionActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemDescription);
    jMenu1.add(jSeparator13);

    jMenuItemDictionary.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemDictionary.setText("Disctionary");
    jMenuItemDictionary.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemDictionaryActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemDictionary);
    jMenu1.add(jSeparator3);

    jMenuBar1.add(jMenu1);

    jMenu3.setText("Search ");
    jMenu3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenu3ActionPerformed(evt);
        }
    });

    jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem4.setText("Query the database");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem4ActionPerformed(evt);
        }
    });
    jMenu3.add(jMenuItem4);

    jMenuBar1.add(jMenu3);

    jMenu2.setText("?");
    jMenu2.setToolTipText("More details about the SEREDATA ?");

    jMenuItemDiscover.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemDiscover.setText("Discover LabEX SERENADE");
    jMenuItemDiscover.setToolTipText("Know more about the SERENADE lab ?");
    jMenuItemDiscover.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemDiscoverActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItemDiscover);
    jMenu2.add(jSeparator14);

    jMenuItemHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemHelp.setText("Help");
    jMenuItemHelp.setToolTipText("Need some help ? ");
    jMenuItemHelp.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemHelpActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItemHelp);
    jMenu2.add(jSeparator5);

    jMenuItemAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemAbout.setText("About");
    jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemAboutActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItemAbout);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPeopleIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPeopleIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPeopleIDActionPerformed

    private void jTextFieldInstitutionIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInstitutionIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInstitutionIDActionPerformed

    private void jButtonAddBibliographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBibliographyActionPerformed
          //add a new cient
        
        //get data from the fields
        try{
            int peopleID = Integer.parseInt(jTextFieldPeopleID.getText());
            int institutionID = Integer.parseInt(jTextFieldInstitutionID.getText());
            String doi = jTextFieldIDOI.getText();
        
            if(bibliography.addBibliography(peopleID, institutionID, doi))
            {
                JOptionPane.showMessageDialog(rootPane, "New Bibliography added Successfully", "Add Bibliography", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Bibliography Not Added ", "Add Bibliography Error", JOptionPane.ERROR_MESSAGE);
            }
            } catch(NumberFormatException ex)
                    {
                       JOptionPane.showMessageDialog(rootPane, "Required Fields -> People ID + Institution ID + DOI.", "Empty Fields", JOptionPane.WARNING_MESSAGE);
                    }
        //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"Bibliography ID", "People ID", "Institution ID", "DOI"}));
       
        // then populate the JTable
        bibliography.fillBibliographyJTable(jTable1);
                       
    }//GEN-LAST:event_jButtonAddBibliographyActionPerformed
 private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        //display the selected row data in the jtextfields
        
        //get the jlabel model 
        DefaultTableModel model = (DefaultTableModel )jTable1.getModel();
                
        // get the selected row index
        int rIndex = jTable1.getSelectedRow();
        
        //display data 
        jTextFieldBibliographyID.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldPeopleID.setText(model.getValueAt(rIndex, 1).toString());
        jTextFieldInstitutionID.setText(model.getValueAt(rIndex, 2).toString());
        jTextFieldIDOI.setText(model.getValueAt(rIndex, 3).toString());
    }                              
 
    private void jButtonClearBibliographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearBibliographyActionPerformed
        // remove text from all jTextfields
        jTextFieldBibliographyID.setText("");
        jTextFieldPeopleID.setText("");
        jTextFieldInstitutionID.setText("");
        jTextFieldIDOI.setText("");
        
    }//GEN-LAST:event_jButtonClearBibliographyActionPerformed

    private void jTextFieldBibliographyIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldBibliographyIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldBibliographyIDActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        //clear the JTable first
       //jTable1.setModel(new DefaultTableModel(null, new Object[]{"Bibliography ID", "People ID", "Institution ID", "DOI"}));
       this.toBack();
        setVisible(false);
        // then populate the JTable
        //bibliography.fillBibliographyJTable(jTable1);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonEditBibliographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditBibliographyActionPerformed
        //get data from the fields
        try{
            int bibliographyID = Integer.valueOf(jTextFieldBibliographyID.getText());
            int peopleID = Integer.parseInt(jTextFieldPeopleID.getText());
            int institutionID = Integer.parseInt(jTextFieldInstitutionID.getText());
            String doi = jTextFieldIDOI.getText();
        
            if(bibliography.editBibliography(bibliographyID, peopleID, institutionID, doi))
                {
                    JOptionPane.showMessageDialog(rootPane, "Bibliography Data Updated Successfully", "Edit Bibliography", JOptionPane.INFORMATION_MESSAGE);
                }else{
                    JOptionPane.showMessageDialog(rootPane, "Bibliography Data Not Updated ", "Edit Bibliography Error", JOptionPane.ERROR_MESSAGE);
                }
        } catch(NumberFormatException ex)
                {
                    JOptionPane.showMessageDialog(rootPane, "Enter The Bibliography Id ", "Bibliography ID Error", JOptionPane.WARNING_MESSAGE);
                }
        //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"Bibliography ID", "People ID", "Institution ID", "DOI"}));
       
        // then populate the JTable
        bibliography.fillBibliographyJTable(jTable1);
    
    }//GEN-LAST:event_jButtonEditBibliographyActionPerformed

    private void jButtonRemoveBibliographyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveBibliographyActionPerformed
         // Delete the selected client
        try{
                    int bibliographyID = Integer.valueOf(jTextFieldBibliographyID.getText());
                    
                    if(bibliography.removeBibliography(bibliographyID))
                        {
                            JOptionPane.showMessageDialog(rootPane, "Bibliography Deleted Successfully", "Remove Bibliography", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                            JOptionPane.showMessageDialog(rootPane, "Bibliography Not Deleted ", "Remove Bibliography Error", JOptionPane.ERROR_MESSAGE);
                        }
               }
              catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Bibliography Id", "Bibliography ID Error", JOptionPane.ERROR_MESSAGE);
            }
        //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"Bibliography ID", "People ID", "Institution ID", "DOI"}));
       
        // then populate the JTable
        bibliography.fillBibliographyJTable(jTable1);
    }//GEN-LAST:event_jButtonRemoveBibliographyActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItemMesocosmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMesocosmsActionPerformed
        // open the manage Rooms form
        ManageMesocosmsFormLONG mesocosmForm = new ManageMesocosmsFormLONG();
        mesocosmForm.setVisible(true);
        mesocosmForm.pack();
        mesocosmForm.setLocationRelativeTo(null);
        mesocosmForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemMesocosmsActionPerformed

    private void jMenuItemPublicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPublicationsActionPerformed
        // open the Discover SERENADE form
        ManagePublicationForm publicationForm = new ManagePublicationForm();
        publicationForm.setVisible(true);
        publicationForm.pack();
        publicationForm.setLocationRelativeTo(null);
        publicationForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemPublicationsActionPerformed

    private void jMenuItemInstitutionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInstitutionsActionPerformed
        // open the Institution form
        ManageInstitutionForm institutionForm = new ManageInstitutionForm();
        institutionForm.setVisible(true);
        institutionForm.pack();
        institutionForm.setLocationRelativeTo(null);
        institutionForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemInstitutionsActionPerformed

    private void jMenuItemBibliograpgyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBibliograpgyActionPerformed
        // open the bibliography form
        ManageBibliographyForm bibliograpgyForm = new ManageBibliographyForm();
        bibliograpgyForm.setVisible(true);
        bibliograpgyForm.pack();
        bibliograpgyForm.setLocationRelativeTo(null);
        bibliograpgyForm.setExtendedState(JFrame.MAXIMIZED_BOTH);
        bibliograpgyForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemBibliograpgyActionPerformed

    private void jMenuItemPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPeopleActionPerformed
        // open the Description form
        ManagePeopleForm peopleForm = new ManagePeopleForm();
        peopleForm.setVisible(true);
        peopleForm.pack();
        peopleForm.setLocationRelativeTo(null);
        peopleForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemPeopleActionPerformed

    private void jMenuItemProtocolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProtocolsActionPerformed
        // open the Manage protocol form
        ManageProtocolForm protocolForm = new ManageProtocolForm();
        protocolForm.setVisible(true);
        protocolForm.pack();
        protocolForm.setLocationRelativeTo(null);
        protocolForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemProtocolsActionPerformed

    private void jMenuItemInstrumentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInstrumentsActionPerformed
        // open the Manage Dictionary form
        ManageInstrumentForm instrumentForm = new ManageInstrumentForm();
        instrumentForm.setVisible(true);
        instrumentForm.pack();
        instrumentForm.setLocationRelativeTo(null);
        instrumentForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemInstrumentsActionPerformed

    private void jMenuItemMeasurementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMeasurementsActionPerformed
        // open the Institution form
        ManageMeasurementForm measurementForm = new ManageMeasurementForm();
        measurementForm.setVisible(true);
        measurementForm.pack();
        measurementForm.setLocationRelativeTo(null);
        measurementForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemMeasurementsActionPerformed

    private void jMenuItemDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDescriptionActionPerformed
        // open the Description form
        ManageDescriptionForm descriptionForm = new ManageDescriptionForm();
        descriptionForm.setVisible(true);
        descriptionForm.pack();
        descriptionForm.setLocationRelativeTo(null);
        descriptionForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemDescriptionActionPerformed

    private void jMenuItemDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDictionaryActionPerformed
        // open the Manage Dictionary form
        ManageDictionaryForm DictionaryForm = new ManageDictionaryForm();
        DictionaryForm.setVisible(true);
        DictionaryForm.pack();
        DictionaryForm.setLocationRelativeTo(null);
        DictionaryForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemDictionaryActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // open the Institution form
        SearchMesocosmsForm searchMesocosmForm = new SearchMesocosmsForm();
        searchMesocosmForm.setVisible(true);
        searchMesocosmForm.pack();
        searchMesocosmForm.setLocationRelativeTo(null);
        searchMesocosmForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
        // open the Institution form
        SearchMesocosmsForm searchMesocosmForm = new SearchMesocosmsForm();
        searchMesocosmForm.setVisible(true);
        searchMesocosmForm.pack();
        searchMesocosmForm.setLocationRelativeTo(null);
        searchMesocosmForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItemDiscoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDiscoverActionPerformed
        // open the Discover SERENADE form
        DiscoverSerenadeForm discoverSerenadeForm = new DiscoverSerenadeForm();
        discoverSerenadeForm.setVisible(true);
        discoverSerenadeForm.pack();
        discoverSerenadeForm.setLocationRelativeTo(null);
        discoverSerenadeForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemDiscoverActionPerformed

    private void jMenuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpActionPerformed
        // open the Help form
        HelpForm helpForm = new HelpForm();
        helpForm.setVisible(true);
        helpForm.pack();
        helpForm.setLocationRelativeTo(null);
        helpForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemHelpActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        // open the About form
        AboutForm aboutForm = new AboutForm();
        aboutForm.setVisible(true);
        aboutForm.pack();
        aboutForm.setLocationRelativeTo(null);
        aboutForm.setExtendedState(JFrame.MAXIMIZED_BOTH);
        aboutForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBibliographyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBibliographyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBibliographyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBibliographyForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBibliographyForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddBibliography;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonClearBibliography;
    private javax.swing.JButton jButtonEditBibliography;
    private javax.swing.JButton jButtonRemoveBibliography;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemBibliograpgy;
    private javax.swing.JMenuItem jMenuItemDescription;
    private javax.swing.JMenuItem jMenuItemDictionary;
    private javax.swing.JMenuItem jMenuItemDiscover;
    private javax.swing.JMenuItem jMenuItemHelp;
    private javax.swing.JMenuItem jMenuItemInstitutions;
    private javax.swing.JMenuItem jMenuItemInstruments;
    private javax.swing.JMenuItem jMenuItemMeasurements;
    private javax.swing.JMenuItem jMenuItemMesocosms;
    private javax.swing.JMenuItem jMenuItemPeople;
    private javax.swing.JMenuItem jMenuItemProtocols;
    private javax.swing.JMenuItem jMenuItemPublications;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldBibliographyID;
    private javax.swing.JTextField jTextFieldIDOI;
    private javax.swing.JTextField jTextFieldInstitutionID;
    private javax.swing.JTextField jTextFieldPeopleID;
    // End of variables declaration//GEN-END:variables
}
