/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaNanoSerenade;

import java.awt.Color;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author aliay
 */
public class ManageInstitutionForm extends javax.swing.JFrame {

     INSTITUTION institution = new INSTITUTION();
    /**
     * Creates new form ManageRoomsForm
     */
    public ManageInstitutionForm() {
        initComponents();
        
        
        GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
 
                if( device.isFullScreenSupported() && !this.isDisplayable() ) {
                    this.setUndecorated(true);
                    device.setFullScreenWindow(this); 
                }else {
                    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
                    this.setResizable(true); // on empêche de redimensionner la fenêtre 
                }
                
         //ajout d une icone serende pour la page
          this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/lloogg_ser.png")).getImage());
        
        //populate the jtable
        institution.fillInstitutionJTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldInstitutionID = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabelNote = new javax.swing.JLabel();
        jTextFieldInstitution = new javax.swing.JTextField();
        jTextFieldDepartment = new javax.swing.JTextField();
        jTextFieldCity = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldState = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldZipcode = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldCountry = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jButtonClearInstitution = new javax.swing.JButton();
        jButtonAddInstitution = new javax.swing.JButton();
        jButtonRemoveInstitution = new javax.swing.JButton();
        jButtonEditInstitution = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMesocosms = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPublications = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemInstitutions = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItemBibliograpgy = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPeople = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItemProtocols = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItemInstruments = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMeasurements = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItemDescription = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItemDictionary = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemDiscover = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItemHelp = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAbout = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Institution");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Institution informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Institution ID:");

        jTextFieldInstitutionID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldInstitutionID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldInstitutionIDActionPerformed(evt);
            }
        });

        jLabel57.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Department");

        jLabelNote.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabelNote.setText("Institution:");

        jTextFieldInstitution.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldDepartment.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDepartmentActionPerformed(evt);
            }
        });

        jTextFieldCity.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCityActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("City:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("State:");

        jTextFieldState.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldState.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStateActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setText("Zipcode:");

        jTextFieldZipcode.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldZipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldZipcodeActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel15.setText("Country:");

        jTextFieldCountry.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCountryActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(jLabel57)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel58)
                .addGap(45, 45, 45)
                .addComponent(jLabel52))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldState, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldInstitutionID, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jTextFieldDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabelNote))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jTextFieldInstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldInstitutionID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldDepartment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jTextFieldInstitution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelNote, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCountry, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel15))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldZipcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel13)))
                .addGap(20, 20, 20)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jLabel58)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Institution ID", "Department", "Institution", "City", "State", "Zipcode", "Country"
            }
        )
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTable1.setGridColor(new java.awt.Color(204, 255, 0));

    jTable1.setSelectionBackground(new java.awt.Color(0, 153, 0));

    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jButtonBack.setBackground(new java.awt.Color(204, 204, 204));
    jButtonBack.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/back_button.png"))); // NOI18N
    jButtonBack.setToolTipText("Click to return to the main window.");
    jButtonBack.setBorderPainted(false);
    jButtonBack.setContentAreaFilled(false);
    jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonBack.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonBackActionPerformed(evt);
        }
    });

    jButtonClearInstitution.setBackground(new java.awt.Color(204, 204, 204));
    jButtonClearInstitution.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonClearInstitution.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/reset_button.png"))); // NOI18N
    jButtonClearInstitution.setToolTipText("Click to clear the fields.");
    jButtonClearInstitution.setBorderPainted(false);
    jButtonClearInstitution.setContentAreaFilled(false);
    jButtonClearInstitution.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonClearInstitution.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonClearInstitutionActionPerformed(evt);
        }
    });

    jButtonAddInstitution.setBackground(new java.awt.Color(204, 204, 204));
    jButtonAddInstitution.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonAddInstitution.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/save_button.png"))); // NOI18N
    jButtonAddInstitution.setToolTipText("Click to add a new institution.");
    jButtonAddInstitution.setBorderPainted(false);
    jButtonAddInstitution.setContentAreaFilled(false);
    jButtonAddInstitution.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonAddInstitution.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAddInstitutionActionPerformed(evt);
        }
    });

    jButtonRemoveInstitution.setBackground(new java.awt.Color(204, 204, 204));
    jButtonRemoveInstitution.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonRemoveInstitution.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/remove_button.png"))); // NOI18N
    jButtonRemoveInstitution.setToolTipText("Click to delete the selected institution.");
    jButtonRemoveInstitution.setBorderPainted(false);
    jButtonRemoveInstitution.setContentAreaFilled(false);
    jButtonRemoveInstitution.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRemoveInstitution.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRemoveInstitutionActionPerformed(evt);
        }
    });

    jButtonEditInstitution.setBackground(new java.awt.Color(204, 204, 204));
    jButtonEditInstitution.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonEditInstitution.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/edit_button.png"))); // NOI18N
    jButtonEditInstitution.setToolTipText("Click to edit the details of the selected institution.");
    jButtonEditInstitution.setBorderPainted(false);
    jButtonEditInstitution.setContentAreaFilled(false);
    jButtonEditInstitution.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonEditInstitution.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonEditInstitutionActionPerformed(evt);
        }
    });

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/exit_button.png"))); // NOI18N
    jButton1.setToolTipText("Click to close the application.");
    jButton1.setBorderPainted(false);
    jButton1.setContentAreaFilled(false);
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(31, 31, 31)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(95, 95, 95)
                    .addComponent(jButtonAddInstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(32, 32, 32)
                    .addComponent(jButtonEditInstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(43, 43, 43)
                    .addComponent(jButtonRemoveInstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(54, 54, 54)
                    .addComponent(jButtonClearInstitution, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(61, 61, 61)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(51, 51, 51)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(38, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButtonEditInstitution)
                .addComponent(jButtonRemoveInstitution)
                .addComponent(jButtonAddInstitution)
                .addComponent(jButtonBack)
                .addComponent(jButtonClearInstitution)
                .addComponent(jButton1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(25, Short.MAX_VALUE))
    );

    jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jMenuBar1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N

    jMenu5.setText("File ");

    jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem3.setText("Properties");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem3ActionPerformed(evt);
        }
    });
    jMenu5.add(jMenuItem3);
    jMenu5.add(jSeparator4);

    jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem2.setText("Exit");
    jMenuItem2.setToolTipText("Click to close the application.");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem2ActionPerformed(evt);
        }
    });
    jMenu5.add(jMenuItem2);

    jMenuBar1.add(jMenu5);

    jMenu1.setText("Edit >");
    jMenu1.add(jSeparator1);

    jMenuItemMesocosms.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemMesocosms.setText("Mesocosms");
    jMenuItemMesocosms.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemMesocosmsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemMesocosms);
    jMenu1.add(jSeparator2);

    jMenuItemPublications.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemPublications.setText("Publications");
    jMenuItemPublications.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemPublicationsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemPublications);
    jMenu1.add(jSeparator6);

    jMenuItemInstitutions.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemInstitutions.setText("Instutitions");
    jMenuItemInstitutions.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemInstitutionsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemInstitutions);
    jMenu1.add(jSeparator7);

    jMenuItemBibliograpgy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemBibliograpgy.setText("Bibliograpgy");
    jMenuItemBibliograpgy.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemBibliograpgyActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemBibliograpgy);
    jMenu1.add(jSeparator8);

    jMenuItemPeople.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemPeople.setText("People");
    jMenuItemPeople.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemPeopleActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemPeople);
    jMenu1.add(jSeparator9);

    jMenuItemProtocols.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemProtocols.setText("Protocols");
    jMenuItemProtocols.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemProtocolsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemProtocols);
    jMenu1.add(jSeparator10);

    jMenuItemInstruments.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemInstruments.setText("Instruments");
    jMenuItemInstruments.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemInstrumentsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemInstruments);
    jMenu1.add(jSeparator11);

    jMenuItemMeasurements.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemMeasurements.setText("Measurements");
    jMenuItemMeasurements.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemMeasurementsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemMeasurements);
    jMenu1.add(jSeparator12);

    jMenuItemDescription.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemDescription.setText("Description");
    jMenuItemDescription.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemDescriptionActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemDescription);
    jMenu1.add(jSeparator13);

    jMenuItemDictionary.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemDictionary.setText("Disctionary");
    jMenuItemDictionary.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemDictionaryActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemDictionary);
    jMenu1.add(jSeparator3);

    jMenuBar1.add(jMenu1);

    jMenu3.setText("Search ");
    jMenu3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenu3ActionPerformed(evt);
        }
    });

    jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem4.setText("Query the database");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem4ActionPerformed(evt);
        }
    });
    jMenu3.add(jMenuItem4);

    jMenuBar1.add(jMenu3);

    jMenu2.setText("?");
    jMenu2.setToolTipText("More details about the SEREDATA ?");

    jMenuItemDiscover.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemDiscover.setText("Discover LabEX SERENADE");
    jMenuItemDiscover.setToolTipText("Know more about the SERENADE lab ?");
    jMenuItemDiscover.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemDiscoverActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItemDiscover);
    jMenu2.add(jSeparator14);

    jMenuItemHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemHelp.setText("Help");
    jMenuItemHelp.setToolTipText("Need some help ? ");
    jMenuItemHelp.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemHelpActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItemHelp);
    jMenu2.add(jSeparator5);

    jMenuItemAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemAbout.setText("About");
    jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemAboutActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItemAbout);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldInstitutionIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldInstitutionIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldInstitutionIDActionPerformed

    private void jTextFieldDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDepartmentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDepartmentActionPerformed

    private void jTextFieldCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCityActionPerformed

    private void jTextFieldStateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStateActionPerformed

    private void jTextFieldZipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldZipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldZipcodeActionPerformed

    private void jTextFieldCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCountryActionPerformed

    private void jButtonAddInstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddInstitutionActionPerformed
         //add a new cient
        
        //get data from the fields
        String department = jTextFieldDepartment.getText();
        String pinstitution = jTextFieldInstitution.getText();
        String city = jTextFieldCity.getText();
        String state = jTextFieldState.getText();
        String zipcode = jTextFieldZipcode.getText();
        String country = jTextFieldCountry.getText();
        
        if(department.trim().equals("") || pinstitution.trim().equals("") || city.trim().equals("") || state.trim().equals("") || zipcode.trim().equals("") || country.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Required Fields -> Department + Institution + City + State + Zipcode + Country.", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else {
            if(institution.addInstitution(department, pinstitution, city, state, zipcode, country))
            {
                JOptionPane.showMessageDialog(rootPane, "New Institution added Successfully", "Add Institution", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Institution Not Added ", "Add Institution Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        //clear the JTable first
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"Institution ID", "Department", "Institution", "City", "State", "Zipcode", "Country"}));
        
        // then populate the JTable
        institution.fillInstitutionJTable(jTable1);
    }//GEN-LAST:event_jButtonAddInstitutionActionPerformed
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        //display the selected row data in the jtextfields
        
        //get the jlabel model 
        DefaultTableModel model = (DefaultTableModel )jTable1.getModel();
                
        // get the selected row index
        int rIndex = jTable1.getSelectedRow();
        
        //display data 
        jTextFieldInstitutionID.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldDepartment.setText(model.getValueAt(rIndex, 1).toString());
        jTextFieldInstitution.setText(model.getValueAt(rIndex, 2).toString());
        jTextFieldCity.setText(model.getValueAt(rIndex, 3).toString());
        jTextFieldState.setText(model.getValueAt(rIndex, 4).toString());
        jTextFieldZipcode.setText(model.getValueAt(rIndex, 5).toString());
        jTextFieldCountry.setText(model.getValueAt(rIndex, 6).toString());
    }                                    
    private void jButtonClearInstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearInstitutionActionPerformed
        // remove text from all jTextfields
        jTextFieldCity.setText("");
        jTextFieldCountry.setText("");
        jTextFieldDepartment.setText("");
        jTextFieldInstitution.setText("");
        jTextFieldInstitutionID.setText("");
        jTextFieldState.setText("");
        jTextFieldZipcode.setText("");
    }//GEN-LAST:event_jButtonClearInstitutionActionPerformed

    private void jButtonEditInstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditInstitutionActionPerformed
         // EDIT THE SELECTED CLIENT
        
        //get data from the fields
        int institutionID = 0;
        String department = jTextFieldDepartment.getText();
        String pinstitution = jTextFieldInstitution.getText();
        String city = jTextFieldCity.getText();
        String state = jTextFieldState.getText();
        String zipcode = jTextFieldZipcode.getText();
        String country = jTextFieldCountry.getText();
        
          if(department.trim().equals("") || pinstitution.trim().equals("") || city.trim().equals("") || state.trim().equals("") || zipcode.trim().equals("") || country.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Required Fields -> First/Last Name + The Phone Number + The Email.", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else {
              
              try{
                    institutionID = Integer.valueOf(jTextFieldInstitutionID.getText());
                    
                    if(institution.editInstitution(institutionID, department, pinstitution, city, state, zipcode, country))
                        {
                            JOptionPane.showMessageDialog(rootPane, "Institution Data Updated Successfully", "Edit Institution", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                            JOptionPane.showMessageDialog(rootPane, "Institution Data Not Updated ", "Edit Institution Error", JOptionPane.ERROR_MESSAGE);
                        }
               }
              catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Institution Id (number)", "Institution ID Error", JOptionPane.ERROR_MESSAGE);
            }
                      
            
        }
          //clear the JTable first
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"Institution ID", "Department", "Institution", "City", "State", "Zipcode", "Country"}));
        
        // then populate the JTable
        institution.fillInstitutionJTable(jTable1);
    }//GEN-LAST:event_jButtonEditInstitutionActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        //clear the JTable first
        //jTable1.setModel(new DefaultTableModel(null, new Object[]{"Institution ID", "Department", "Institution", "City", "State", "Zipcode", "Country"}));
        this.toBack();
        setVisible(false);
        // then populate the JTable
        //institution.fillInstitutionJTable(jTable1);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonRemoveInstitutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveInstitutionActionPerformed
         // Delete the selected client
        try{
                    int institutionID = Integer.valueOf(jTextFieldInstitutionID.getText());
                    
                    if(institution.removeInstitution(institutionID))
                        {
                            JOptionPane.showMessageDialog(rootPane, "Institution Deleted Successfully", "Remove Institution", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                            JOptionPane.showMessageDialog(rootPane, "Institution Not Deleted ", "Remove Institution Error", JOptionPane.ERROR_MESSAGE);
                        }
               }
              catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Institution Id ", "Institution ID Error", JOptionPane.ERROR_MESSAGE);
            }
        //clear the JTable first
        jTable1.setModel(new DefaultTableModel(null, new Object[]{"Institution ID", "Department", "Institution", "City", "State", "Zipcode", "Country"}));
        
        // then populate the JTable
        institution.fillInstitutionJTable(jTable1);
    }//GEN-LAST:event_jButtonRemoveInstitutionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemMesocosmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMesocosmsActionPerformed
        // open the manage Rooms form
        ManageMesocosmsFormLONG mesocosmForm = new ManageMesocosmsFormLONG();
        mesocosmForm.setVisible(true);
        mesocosmForm.pack();
        mesocosmForm.setLocationRelativeTo(null);
        mesocosmForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemMesocosmsActionPerformed

    private void jMenuItemPublicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPublicationsActionPerformed
        // open the Discover SERENADE form
        ManagePublicationForm publicationForm = new ManagePublicationForm();
        publicationForm.setVisible(true);
        publicationForm.pack();
        publicationForm.setLocationRelativeTo(null);
        publicationForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemPublicationsActionPerformed

    private void jMenuItemInstitutionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInstitutionsActionPerformed
        // open the Institution form
        ManageInstitutionForm institutionForm = new ManageInstitutionForm();
        institutionForm.setVisible(true);
        institutionForm.pack();
        institutionForm.setLocationRelativeTo(null);
        institutionForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemInstitutionsActionPerformed

    private void jMenuItemBibliograpgyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBibliograpgyActionPerformed
        // open the bibliography form
        ManageBibliographyForm bibliograpgyForm = new ManageBibliographyForm();
        bibliograpgyForm.setVisible(true);
        bibliograpgyForm.pack();
        bibliograpgyForm.setLocationRelativeTo(null);
        bibliograpgyForm.setExtendedState(JFrame.MAXIMIZED_BOTH);
        bibliograpgyForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemBibliograpgyActionPerformed

    private void jMenuItemPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPeopleActionPerformed
        // open the Description form
        ManagePeopleForm peopleForm = new ManagePeopleForm();
        peopleForm.setVisible(true);
        peopleForm.pack();
        peopleForm.setLocationRelativeTo(null);
        peopleForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemPeopleActionPerformed

    private void jMenuItemProtocolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProtocolsActionPerformed
        // open the Manage protocol form
        ManageProtocolForm protocolForm = new ManageProtocolForm();
        protocolForm.setVisible(true);
        protocolForm.pack();
        protocolForm.setLocationRelativeTo(null);
        protocolForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemProtocolsActionPerformed

    private void jMenuItemInstrumentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInstrumentsActionPerformed
        // open the Manage Dictionary form
        ManageInstrumentForm instrumentForm = new ManageInstrumentForm();
        instrumentForm.setVisible(true);
        instrumentForm.pack();
        instrumentForm.setLocationRelativeTo(null);
        instrumentForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemInstrumentsActionPerformed

    private void jMenuItemMeasurementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMeasurementsActionPerformed
        // open the Institution form
        ManageMeasurementForm measurementForm = new ManageMeasurementForm();
        measurementForm.setVisible(true);
        measurementForm.pack();
        measurementForm.setLocationRelativeTo(null);
        measurementForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemMeasurementsActionPerformed

    private void jMenuItemDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDescriptionActionPerformed
        // open the Description form
        ManageDescriptionForm descriptionForm = new ManageDescriptionForm();
        descriptionForm.setVisible(true);
        descriptionForm.pack();
        descriptionForm.setLocationRelativeTo(null);
        descriptionForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemDescriptionActionPerformed

    private void jMenuItemDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDictionaryActionPerformed
        // open the Manage Dictionary form
        ManageDictionaryForm DictionaryForm = new ManageDictionaryForm();
        DictionaryForm.setVisible(true);
        DictionaryForm.pack();
        DictionaryForm.setLocationRelativeTo(null);
        DictionaryForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemDictionaryActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // open the Institution form
        SearchMesocosmsForm searchMesocosmForm = new SearchMesocosmsForm();
        searchMesocosmForm.setVisible(true);
        searchMesocosmForm.pack();
        searchMesocosmForm.setLocationRelativeTo(null);
        searchMesocosmForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
        // open the Institution form
        SearchMesocosmsForm searchMesocosmForm = new SearchMesocosmsForm();
        searchMesocosmForm.setVisible(true);
        searchMesocosmForm.pack();
        searchMesocosmForm.setLocationRelativeTo(null);
        searchMesocosmForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItemDiscoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDiscoverActionPerformed
        // open the Discover SERENADE form
        DiscoverSerenadeForm discoverSerenadeForm = new DiscoverSerenadeForm();
        discoverSerenadeForm.setVisible(true);
        discoverSerenadeForm.pack();
        discoverSerenadeForm.setLocationRelativeTo(null);
        discoverSerenadeForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemDiscoverActionPerformed

    private void jMenuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpActionPerformed
        // open the Help form
        HelpForm helpForm = new HelpForm();
        helpForm.setVisible(true);
        helpForm.pack();
        helpForm.setLocationRelativeTo(null);
        helpForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemHelpActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        // open the About form
        AboutForm aboutForm = new AboutForm();
        aboutForm.setVisible(true);
        aboutForm.pack();
        aboutForm.setLocationRelativeTo(null);
        aboutForm.setExtendedState(JFrame.MAXIMIZED_BOTH);
        aboutForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageInstitutionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageInstitutionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageInstitutionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageInstitutionForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageInstitutionForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddInstitution;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonClearInstitution;
    private javax.swing.JButton jButtonEditInstitution;
    private javax.swing.JButton jButtonRemoveInstitution;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelNote;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemBibliograpgy;
    private javax.swing.JMenuItem jMenuItemDescription;
    private javax.swing.JMenuItem jMenuItemDictionary;
    private javax.swing.JMenuItem jMenuItemDiscover;
    private javax.swing.JMenuItem jMenuItemHelp;
    private javax.swing.JMenuItem jMenuItemInstitutions;
    private javax.swing.JMenuItem jMenuItemInstruments;
    private javax.swing.JMenuItem jMenuItemMeasurements;
    private javax.swing.JMenuItem jMenuItemMesocosms;
    private javax.swing.JMenuItem jMenuItemPeople;
    private javax.swing.JMenuItem jMenuItemProtocols;
    private javax.swing.JMenuItem jMenuItemPublications;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldCountry;
    private javax.swing.JTextField jTextFieldDepartment;
    private javax.swing.JTextField jTextFieldInstitution;
    private javax.swing.JTextField jTextFieldInstitutionID;
    private javax.swing.JTextField jTextFieldState;
    private javax.swing.JTextField jTextFieldZipcode;
    // End of variables declaration//GEN-END:variables
}
