/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaNanoSerenade;

import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author aliay
 */
public class ManageMeasurementForm extends javax.swing.JFrame {

    MEASUREMENT measurement = new MEASUREMENT();
    /**
     * Creates new form ManageRoomsForm
     */
    public ManageMeasurementForm() {
        initComponents();
        
        
        GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
 
                if( device.isFullScreenSupported() && !this.isDisplayable() ) {
                    this.setUndecorated(true);
                    device.setFullScreenWindow(this); 
                }else {
                    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
                    this.setResizable(true); // on empêche de redimensionner la fenêtre 
                }
         //ajout d une icone serende pour la page
          this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/lloogg_ser.png")).getImage());
          
          
         //populate the jtable
        measurement.fillMeasurementJTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextFieldMeasType = new javax.swing.JTextField();
        jTextFieldMeasID = new javax.swing.JTextField();
        jTextFieldDOI = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextFieldSourceID = new javax.swing.JTextField();
        jTextFieldReferencingID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        jTextFieldTimeRelative = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldSourceDOI = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel60 = new javax.swing.JLabel();
        jTextFieldparameterStatistics = new javax.swing.JTextField();
        jTextFieldparameterText = new javax.swing.JTextField();
        jTextFieldParameterDataType = new javax.swing.JTextField();
        jTextFieldParameterDescription = new javax.swing.JTextField();
        jTextFieldParameter = new javax.swing.JTextField();
        jTextFieldTimeAbsolute = new javax.swing.JTextField();
        jTextFieldTimeUnit = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTextFieldinstrumentId = new javax.swing.JTextField();
        jTextFieldProtocolId = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jTextFieldOwnerGroup = new javax.swing.JTextField();
        jTextFieldparameterUncertaintyUpper = new javax.swing.JTextField();
        jTextFieldparameterUncertaintyUnit = new javax.swing.JTextField();
        jTextFieldparameterUncertaintyLow = new javax.swing.JTextField();
        jTextFieldparameterUncertaintyType = new javax.swing.JTextField();
        jTextFieldparameterUnit = new javax.swing.JTextField();
        jTextFieldparameterNumericOperator = new javax.swing.JTextField();
        jTextFieldparameterNumeric = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        jTextFieldInherentID = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonAddMeasurement = new javax.swing.JButton();
        jButtonRemoveMeasurement = new javax.swing.JButton();
        jButtonEditMeasurement = new javax.swing.JButton();
        jButtonClearMeasurement = new javax.swing.JButton();
        jButtonBack = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMesocosms = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPublications = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemInstitutions = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItemBibliograpgy = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPeople = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItemProtocols = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItemInstruments = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMeasurements = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItemDescription = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItemDictionary = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemDiscover = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItemHelp = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAbout = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Measurement");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Measurement informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("DOI:");

        jLabel31.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel31.setText("Measurement ID:");

        jLabel32.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel32.setText("Measurement Type:");

        jTextFieldMeasType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldMeasID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldMeasID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMeasIDActionPerformed(evt);
            }
        });

        jTextFieldDOI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldDOI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDOIActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel37.setText("Source ID:");

        jTextFieldSourceID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldReferencingID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("Referencing ID:");

        jLabel54.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel54.setText("Time Relative:");

        jTextFieldTimeRelative.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel57.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel12.setText("Source DOI:");

        jTextFieldSourceDOI.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Time Unit:");

        jLabel33.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel33.setText("Time Absolute:");

        jLabel34.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel34.setText("Parameter:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel13.setText("Parameter Description:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setText("Parameter DataType:");

        jLabel38.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel38.setText("Parameter Text:");

        jLabel60.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel60.setText("Parameter Statistics:");

        jTextFieldparameterStatistics.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldparameterText.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldParameterDataType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldParameterDescription.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldParameter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldTimeAbsolute.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldTimeUnit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldTimeUnit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTimeUnitActionPerformed(evt);
            }
        });

        jLabel35.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel35.setText("Instrument ID:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel17.setText("Owner Group:");

        jTextFieldinstrumentId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldProtocolId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel36.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel36.setText("Protocol ID:");

        jTextFieldOwnerGroup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldOwnerGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldOwnerGroupActionPerformed(evt);
            }
        });

        jTextFieldparameterUncertaintyUpper.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldparameterUncertaintyUnit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldparameterUncertaintyLow.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldparameterUncertaintyType.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldparameterUnit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldparameterNumericOperator.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldparameterNumeric.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldparameterNumeric.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldparameterNumericActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel18.setText("Parameter Numeric:");

        jLabel40.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel40.setText("Parameter Numeric Operator:");

        jLabel41.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel41.setText("Parameter Unit:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel19.setText("Parameter Uncertainty Type:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel20.setText("Parameter Uncertainty Lower:");

        jLabel42.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel42.setText("Parameter Uncertainty Unit:");

        jLabel62.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel62.setText("Parameter Uncertainty Upper:");

        jTextFieldInherentID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel39.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel39.setText("Inherent ID:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldMeasType, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel13)
                        .addGap(52, 52, 52)
                        .addComponent(jTextFieldParameterDescription, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel42)
                        .addGap(37, 37, 37)
                        .addComponent(jTextFieldparameterUncertaintyUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldReferencingID, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSourceDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(120, 120, 120)
                                .addComponent(jLabel57))
                            .addComponent(jLabel38))
                        .addGap(63, 63, 63)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldParameterDataType, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldparameterText, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel62)
                            .addComponent(jLabel17))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldparameterUncertaintyUpper, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(jLabel58))
                            .addComponent(jTextFieldOwnerGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addGap(66, 66, 66)
                        .addComponent(jTextFieldSourceID, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel60)
                        .addGap(67, 67, 67)
                        .addComponent(jTextFieldparameterStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel36)
                        .addGap(146, 146, 146)
                        .addComponent(jTextFieldProtocolId, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel54)
                        .addGap(44, 44, 44)
                        .addComponent(jTextFieldTimeRelative, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel18)
                        .addGap(72, 72, 72)
                        .addComponent(jTextFieldparameterNumericOperator, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jLabel35)
                        .addGap(124, 124, 124)
                        .addComponent(jTextFieldinstrumentId, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(70, 70, 70)
                        .addComponent(jTextFieldTimeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel40)
                        .addGap(5, 5, 5)
                        .addComponent(jTextFieldparameterNumeric, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(37, 37, 37)
                        .addComponent(jTextFieldTimeAbsolute, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel41)
                        .addGap(101, 101, 101)
                        .addComponent(jTextFieldparameterUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel31)
                                .addGap(20, 20, 20)
                                .addComponent(jTextFieldMeasID, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(107, 107, 107)
                                .addComponent(jTextFieldDOI, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel34)
                                .addGap(134, 134, 134)
                                .addComponent(jTextFieldParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel19)
                                .addGap(31, 31, 31)
                                .addComponent(jTextFieldparameterUncertaintyType, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel39)
                                .addGap(123, 123, 123)
                                .addComponent(jTextFieldInherentID, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldparameterUncertaintyLow, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel9))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldDOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel34))
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldparameterUncertaintyType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel31))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldMeasID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(jLabel39))
                    .addComponent(jTextFieldInherentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldparameterUncertaintyLow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel20)))
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel32))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldMeasType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldParameterDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldparameterUncertaintyUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel42)))
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jTextFieldParameterDataType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldparameterText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldparameterUncertaintyUpper, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel62))
                        .addGap(9, 9, 9)
                        .addComponent(jLabel58)
                        .addGap(3, 3, 3)
                        .addComponent(jTextFieldOwnerGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jLabel12))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jTextFieldReferencingID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(jTextFieldSourceDOI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel10Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel57)
                                .addGap(13, 13, 13)
                                .addComponent(jLabel38)))))
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel37))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldSourceID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel60))
                    .addComponent(jTextFieldparameterStatistics, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel36))
                    .addComponent(jTextFieldProtocolId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel54))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldTimeRelative, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel18))
                    .addComponent(jTextFieldparameterNumericOperator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel35))
                    .addComponent(jTextFieldinstrumentId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel11))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldTimeUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel40))
                    .addComponent(jTextFieldparameterNumeric, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel33))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldTimeAbsolute, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel41))
                    .addComponent(jTextFieldparameterUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DOI", "Measurement ID", "Measurement type", "Referencing ID", "Source DOI", "Source ID", "Time relative", "Time unit", "Time absolute", "Parameter", "Inherit ID", "Parameter description", "Parameter datatype", "Parameter text", "Parameter statistic", "Parameter numeric", "Parameter numeric operator", "Parameter unit", "Parameter uncertainty type", "Parameter uncertainty lower", "Parameter uncertainty upper", "Parameter uncertainty unit", "Owner group", "Protocol ID", "Instrument ID"
            }
        )
        //make the jtable cell not editable
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTable1.setGridColor(new java.awt.Color(204, 255, 0));

    jTable1.setSelectionBackground(new java.awt.Color(0, 153, 0));

    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jButtonAddMeasurement.setBackground(new java.awt.Color(204, 204, 204));
    jButtonAddMeasurement.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonAddMeasurement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/save_button.png"))); // NOI18N
    jButtonAddMeasurement.setToolTipText("Click to add a new measurement.");
    jButtonAddMeasurement.setBorderPainted(false);
    jButtonAddMeasurement.setContentAreaFilled(false);
    jButtonAddMeasurement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonAddMeasurement.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAddMeasurementActionPerformed(evt);
        }
    });

    jButtonRemoveMeasurement.setBackground(new java.awt.Color(204, 204, 204));
    jButtonRemoveMeasurement.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonRemoveMeasurement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/remove_button.png"))); // NOI18N
    jButtonRemoveMeasurement.setToolTipText("Click to delete the selected measurement.");
    jButtonRemoveMeasurement.setBorderPainted(false);
    jButtonRemoveMeasurement.setContentAreaFilled(false);
    jButtonRemoveMeasurement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRemoveMeasurement.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRemoveMeasurementActionPerformed(evt);
        }
    });

    jButtonEditMeasurement.setBackground(new java.awt.Color(204, 204, 204));
    jButtonEditMeasurement.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonEditMeasurement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/edit_button.png"))); // NOI18N
    jButtonEditMeasurement.setToolTipText("Click to edit the details of the selected measurement. ");
    jButtonEditMeasurement.setBorderPainted(false);
    jButtonEditMeasurement.setContentAreaFilled(false);
    jButtonEditMeasurement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonEditMeasurement.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonEditMeasurementActionPerformed(evt);
        }
    });

    jButtonClearMeasurement.setBackground(new java.awt.Color(204, 204, 204));
    jButtonClearMeasurement.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonClearMeasurement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/reset_button.png"))); // NOI18N
    jButtonClearMeasurement.setToolTipText("Click to clear the fields.");
    jButtonClearMeasurement.setBorderPainted(false);
    jButtonClearMeasurement.setContentAreaFilled(false);
    jButtonClearMeasurement.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonClearMeasurement.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonClearMeasurementActionPerformed(evt);
        }
    });

    jButtonBack.setBackground(new java.awt.Color(204, 204, 204));
    jButtonBack.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/back_button.png"))); // NOI18N
    jButtonBack.setToolTipText("Click to return to the main window.");
    jButtonBack.setBorderPainted(false);
    jButtonBack.setContentAreaFilled(false);
    jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonBack.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonBackActionPerformed(evt);
        }
    });

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/exit_button.png"))); // NOI18N
    jButton1.setToolTipText("Click to close the application.");
    jButton1.setBorderPainted(false);
    jButton1.setContentAreaFilled(false);
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(52, 52, 52)
                    .addComponent(jButtonAddMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(75, 75, 75)
                    .addComponent(jButtonEditMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(75, 75, 75)
                    .addComponent(jButtonRemoveMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(75, 75, 75)
                    .addComponent(jButtonClearMeasurement, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(75, 75, 75)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(75, 75, 75)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(24, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jButtonBack)
                .addComponent(jButtonClearMeasurement)
                .addComponent(jButtonRemoveMeasurement)
                .addComponent(jButtonEditMeasurement)
                .addComponent(jButtonAddMeasurement)
                .addComponent(jButton1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(123, Short.MAX_VALUE))
    );

    jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jMenuBar1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N

    jMenu5.setText("File ");

    jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem3.setText("Properties");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem3ActionPerformed(evt);
        }
    });
    jMenu5.add(jMenuItem3);
    jMenu5.add(jSeparator4);

    jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem2.setText("Exit");
    jMenuItem2.setToolTipText("Click to close the application.");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem2ActionPerformed(evt);
        }
    });
    jMenu5.add(jMenuItem2);

    jMenuBar1.add(jMenu5);

    jMenu1.setText("Edit >");
    jMenu1.add(jSeparator1);

    jMenuItemMesocosms.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemMesocosms.setText("Mesocosms");
    jMenuItemMesocosms.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemMesocosmsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemMesocosms);
    jMenu1.add(jSeparator2);

    jMenuItemPublications.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemPublications.setText("Publications");
    jMenuItemPublications.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemPublicationsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemPublications);
    jMenu1.add(jSeparator6);

    jMenuItemInstitutions.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemInstitutions.setText("Instutitions");
    jMenuItemInstitutions.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemInstitutionsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemInstitutions);
    jMenu1.add(jSeparator7);

    jMenuItemBibliograpgy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemBibliograpgy.setText("Bibliograpgy");
    jMenuItemBibliograpgy.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemBibliograpgyActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemBibliograpgy);
    jMenu1.add(jSeparator8);

    jMenuItemPeople.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemPeople.setText("People");
    jMenuItemPeople.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemPeopleActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemPeople);
    jMenu1.add(jSeparator9);

    jMenuItemProtocols.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemProtocols.setText("Protocols");
    jMenuItemProtocols.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemProtocolsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemProtocols);
    jMenu1.add(jSeparator10);

    jMenuItemInstruments.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemInstruments.setText("Instruments");
    jMenuItemInstruments.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemInstrumentsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemInstruments);
    jMenu1.add(jSeparator11);

    jMenuItemMeasurements.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemMeasurements.setText("Measurements");
    jMenuItemMeasurements.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemMeasurementsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemMeasurements);
    jMenu1.add(jSeparator12);

    jMenuItemDescription.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemDescription.setText("Description");
    jMenuItemDescription.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemDescriptionActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemDescription);
    jMenu1.add(jSeparator13);

    jMenuItemDictionary.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemDictionary.setText("Disctionary");
    jMenuItemDictionary.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemDictionaryActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemDictionary);
    jMenu1.add(jSeparator3);

    jMenuBar1.add(jMenu1);

    jMenu3.setText("Search ");
    jMenu3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenu3ActionPerformed(evt);
        }
    });

    jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem4.setText("Query the database");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem4ActionPerformed(evt);
        }
    });
    jMenu3.add(jMenuItem4);

    jMenuBar1.add(jMenu3);

    jMenu2.setText("?");
    jMenu2.setToolTipText("More details about the SEREDATA ?");

    jMenuItemDiscover.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemDiscover.setText("Discover LabEX SERENADE");
    jMenuItemDiscover.setToolTipText("Know more about the SERENADE lab ?");
    jMenuItemDiscover.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemDiscoverActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItemDiscover);
    jMenu2.add(jSeparator14);

    jMenuItemHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemHelp.setText("Help");
    jMenuItemHelp.setToolTipText("Need some help ? ");
    jMenuItemHelp.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemHelpActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItemHelp);
    jMenu2.add(jSeparator5);

    jMenuItemAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemAbout.setText("About");
    jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemAboutActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItemAbout);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldDOIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDOIActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDOIActionPerformed

    private void jTextFieldTimeUnitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTimeUnitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTimeUnitActionPerformed

    private void jTextFieldOwnerGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldOwnerGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldOwnerGroupActionPerformed

    private void jTextFieldparameterNumericActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldparameterNumericActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldparameterNumericActionPerformed

    private void jButtonAddMeasurementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddMeasurementActionPerformed
         //get data from jtextfields
       try{
            String doi = jTextFieldDOI.getText();
            int measurementID = Integer.parseInt(jTextFieldMeasID.getText());
            String measurementType = jTextFieldMeasType.getText();
            int referencingID = Integer.parseInt(jTextFieldReferencingID.getText());
            String sourceDOI = jTextFieldSourceDOI.getText();
            int sourceID = Integer.parseInt(jTextFieldSourceID.getText());
            float timeRelative = Integer.parseInt(jTextFieldTimeRelative.getText());
            String timeUnit = jTextFieldTimeUnit.getText();
            float timeAbsolute = Float.parseFloat(jTextFieldTimeAbsolute.getText());
            String parameter = jTextFieldParameter.getText();
            int inheritID = Integer.parseInt(jTextFieldInherentID.getText());
            String parameterDescription = jTextFieldParameterDescription.getText();
            String parameterDataType = jTextFieldParameterDataType.getText();
            String parameterText = jTextFieldparameterText.getText();
            String parameterStatistic = jTextFieldparameterStatistics.getText();
            float parameterNumeric = Float.parseFloat(jTextFieldparameterNumeric.getText());
            String parameterNumericOperator = jTextFieldparameterNumericOperator.getText();
            int parameterUnit = Integer.parseInt(jTextFieldparameterUnit.getText());
            String parameterUncertaintyType = jTextFieldparameterUncertaintyType.getText();
            float parameterUncertaintyLower = Float.parseFloat(jTextFieldparameterUncertaintyLow.getText());
            float parameterUncertaintyUpper = Float.parseFloat(jTextFieldparameterUncertaintyUpper.getText());
            String parameterUncertaintyUnit = jTextFieldparameterUncertaintyUnit.getText();
            int ownerGroup = Integer.parseInt(jTextFieldOwnerGroup.getText());
            int protocolID = Integer.parseInt(jTextFieldProtocolId.getText());
            int instrumentID = Integer.parseInt(jTextFieldinstrumentId.getText());
        
            if(measurement.addMeasurement(doi, measurementID, measurementType, referencingID, sourceDOI, sourceID, timeRelative, timeUnit, timeAbsolute, parameter, inheritID, parameterDescription, parameterDataType, parameterText, parameterStatistic, parameterNumeric, parameterNumericOperator, parameterUnit, parameterUncertaintyType, parameterUncertaintyLower, parameterUncertaintyUpper, parameterUncertaintyUnit, ownerGroup, protocolID, instrumentID))
            {
                JOptionPane.showMessageDialog(rootPane, "New Measurement added Successfully", "Add Measurement", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Measurement Not Added ", "Add Measurement Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Measurement ID", "Measurement ID Error", JOptionPane.ERROR_MESSAGE);
            }
       //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"DOI", "Measurement ID", "Measurement type", "Referencing ID", "Source DOI", "Source ID", "Time relative", "Time unit", "Time absolute", "Parameter", "Inherit ID", "Parameter description", "Parameter datatype", "Parameter text", "Parameter statistic", "Parameter numeric", "Parameter numeric operator", "Parameter unit", "Parameter uncertainty type", "Parameter uncertainty lower", "Parameter uncertainty upper", "Parameter uncertainty unit", "Owner group", "Protocol ID", "Instrument ID"}));
       
        // then populate the JTable
        measurement.fillMeasurementJTable(jTable1);
    }//GEN-LAST:event_jButtonAddMeasurementActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        //display the selected row data in the jtextfields
        
        //get the jlabel model 
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                
        // get the selected row index
        int rIndex = jTable1.getSelectedRow();
        
        //display data 
        jTextFieldDOI.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldMeasID.setText(model.getValueAt(rIndex, 1).toString());
        jTextFieldMeasType.setText(model.getValueAt(rIndex, 2).toString());
        //String injectionMode = jComboBoxInjection.getSelectedItem().toString();
        //String ecosystem = jComboBoxEcosystem.getSelectedItem().toString();
        jTextFieldReferencingID.setText(model.getValueAt(rIndex, 3).toString());
        jTextFieldSourceDOI.setText(model.getValueAt(rIndex, 4).toString());
        jTextFieldSourceID.setText(model.getValueAt(rIndex, 5).toString());
        jTextFieldTimeRelative.setText(model.getValueAt(rIndex, 6).toString());
        jTextFieldTimeUnit.setText(model.getValueAt(rIndex, 7).toString());
        jTextFieldTimeAbsolute.setText(model.getValueAt(rIndex, 8).toString());
        jTextFieldParameter.setText(model.getValueAt(rIndex, 9).toString());
        jTextFieldInherentID.setText(model.getValueAt(rIndex, 10).toString());
        jTextFieldParameterDescription.setText(model.getValueAt(rIndex, 11).toString());
        jTextFieldParameterDataType.setText(model.getValueAt(rIndex, 12).toString());
        jTextFieldparameterText.setText(model.getValueAt(rIndex, 13).toString());
        jTextFieldparameterStatistics.setText(model.getValueAt(rIndex, 14).toString());
        jTextFieldparameterNumeric.setText(model.getValueAt(rIndex, 15).toString());
        jTextFieldparameterNumericOperator.setText(model.getValueAt(rIndex, 16).toString());
        jTextFieldparameterUnit.setText(model.getValueAt(rIndex, 17).toString());
        jTextFieldparameterUncertaintyType.setText(model.getValueAt(rIndex, 19).toString());
        jTextFieldparameterUncertaintyLow.setText(model.getValueAt(rIndex, 20).toString());
        jTextFieldparameterUncertaintyUpper.setText(model.getValueAt(rIndex, 21).toString());
        jTextFieldparameterUncertaintyUnit.setText(model.getValueAt(rIndex, 22).toString());
        jTextFieldOwnerGroup.setText(model.getValueAt(rIndex, 23).toString());
        jTextFieldProtocolId.setText(model.getValueAt(rIndex, 24).toString());
        jTextFieldinstrumentId.setText(model.getValueAt(rIndex, 25).toString());
        
               
    }
    
    private void jButtonClearMeasurementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearMeasurementActionPerformed
        // remove text from all jTextfields
        jTextFieldMeasID.setText("");
        jTextFieldMeasType.setText("");
        jTextFieldOwnerGroup.setText("");
        jTextFieldParameter.setText("");
        jTextFieldDOI.setText("");
        jTextFieldParameterDataType.setText("");
        jTextFieldParameterDescription.setText("");
        jTextFieldProtocolId.setText("");
        jTextFieldReferencingID.setText("");
        jTextFieldSourceDOI.setText("");
        jTextFieldSourceID.setText("");
        jTextFieldTimeAbsolute.setText("");
        jTextFieldTimeRelative.setText("");
        jTextFieldTimeUnit.setText("");
        jTextFieldinstrumentId.setText("");
        jTextFieldparameterNumeric.setText("");
        jTextFieldparameterNumericOperator.setText("");
        jTextFieldparameterStatistics.setText("");
        jTextFieldparameterText.setText("");
        jTextFieldparameterUncertaintyLow.setText("");
        jTextFieldparameterUncertaintyType.setText("");
        jTextFieldparameterUncertaintyUnit.setText("");
        jTextFieldparameterUncertaintyUpper.setText("");
        jTextFieldparameterUnit.setText("");
        
    }//GEN-LAST:event_jButtonClearMeasurementActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
         //clear the JTable first
      // jTable1.setModel(new DefaultTableModel(null, new Object[]{"DOI", "Measurement ID", "Measurement type", "Referencing ID", "Source DOI", "Source ID", "Time relative", "Time unit", "Time absolute", "Parameter", "Inherit ID", "Parameter description", "Parameter datatype", "Parameter text", "Parameter statistic", "Parameter numeric", "Parameter numeric operator", "Parameter unit", "Parameter uncertainty type", "Parameter uncertainty lower", "Parameter uncertainty upper", "Parameter uncertainty unit", "Owner group", "Protocol ID", "Instrument ID"}));
       this.toBack();
        setVisible(false);
        // then populate the JTable
        //measurement.fillMeasurementJTable(jTable1);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButtonRemoveMeasurementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveMeasurementActionPerformed
        try{
                    String doi = jTextFieldDOI.getText();
                    
                    if(measurement.removeMeasurement(doi))
                        {
                            JOptionPane.showMessageDialog(rootPane, "Measurement Deleted Successfully", "Remove Measurement", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                            JOptionPane.showMessageDialog(rootPane, "Measurement Not Deleted ", "Remove Measurement Error", JOptionPane.ERROR_MESSAGE);
                        }
               }
              catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Measurement Id ", "Measurement ID Error", JOptionPane.ERROR_MESSAGE);
            }
        //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"DOI", "Measurement ID", "Measurement type", "Referencing ID", "Source DOI", "Source ID", "Time relative", "Time unit", "Time absolute", "Parameter", "Inherit ID", "Parameter description", "Parameter datatype", "Parameter text", "Parameter statistic", "Parameter numeric", "Parameter numeric operator", "Parameter unit", "Parameter uncertainty type", "Parameter uncertainty lower", "Parameter uncertainty upper", "Parameter uncertainty unit", "Owner group", "Protocol ID", "Instrument ID"}));
       
        // then populate the JTable
        measurement.fillMeasurementJTable(jTable1);
    }//GEN-LAST:event_jButtonRemoveMeasurementActionPerformed

    private void jButtonEditMeasurementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditMeasurementActionPerformed
        // EDIT THE SELECTED CLIENT
        
        //get data from the fields
    try{
            String doi = jTextFieldDOI.getText();
            int measurementID = Integer.parseInt(jTextFieldMeasID.getText());
            String measurementType = jTextFieldMeasType.getText();
            int referencingID = Integer.parseInt(jTextFieldReferencingID.getText());
            String sourceDOI = jTextFieldSourceDOI.getText();
            int sourceID = Integer.parseInt(jTextFieldSourceID.getText());
            float timeRelative = Integer.parseInt(jTextFieldTimeRelative.getText());
            String timeUnit = jTextFieldTimeUnit.getText();
            float timeAbsolute = Float.parseFloat(jTextFieldTimeAbsolute.getText());
            String parameter = jTextFieldParameter.getText();
            int inheritID = Integer.parseInt(jTextFieldInherentID.getText());
            String parameterDescription = jTextFieldParameterDescription.getText();
            String parameterDataType = jTextFieldParameterDataType.getText();
            String parameterText = jTextFieldparameterText.getText();
            String parameterStatistic = jTextFieldparameterStatistics.getText();
            float parameterNumeric = Float.parseFloat(jTextFieldparameterNumeric.getText());
            String parameterNumericOperator = jTextFieldparameterNumericOperator.getText();
            int parameterUnit = Integer.parseInt(jTextFieldparameterUnit.getText());
            String parameterUncertaintyType = jTextFieldparameterUncertaintyType.getText();
            float parameterUncertaintyLower = Float.parseFloat(jTextFieldparameterUncertaintyLow.getText());
            float parameterUncertaintyUpper = Float.parseFloat(jTextFieldparameterUncertaintyUpper.getText());
            String parameterUncertaintyUnit = jTextFieldparameterUncertaintyUnit.getText();
            int ownerGroup = Integer.parseInt(jTextFieldOwnerGroup.getText());
            int protocolID = Integer.parseInt(jTextFieldProtocolId.getText());
            int instrumentID = Integer.parseInt(jTextFieldinstrumentId.getText());
        
          
                      
         if(measurement.editMeasurement(doi, measurementID, measurementType, referencingID, sourceDOI, sourceID, timeRelative, timeUnit, timeAbsolute, parameter, inheritID, parameterDescription, parameterDataType, parameterText, parameterStatistic, parameterNumeric, parameterNumericOperator, parameterUnit, parameterUncertaintyType, parameterUncertaintyLower, parameterUncertaintyUpper, parameterUncertaintyUnit, ownerGroup, protocolID, instrumentID))
            {
                JOptionPane.showMessageDialog(rootPane, "Measurement Data Updated Successfully", "Edit Measurement", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Measurement Data Not Updated ", "Edit Measurement Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Measurement ID", "Measurement ID Error", JOptionPane.ERROR_MESSAGE);
            }
    //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"DOI", "Measurement ID", "Measurement type", "Referencing ID", "Source DOI", "Source ID", "Time relative", "Time unit", "Time absolute", "Parameter", "Inherit ID", "Parameter description", "Parameter datatype", "Parameter text", "Parameter statistic", "Parameter numeric", "Parameter numeric operator", "Parameter unit", "Parameter uncertainty type", "Parameter uncertainty lower", "Parameter uncertainty upper", "Parameter uncertainty unit", "Owner group", "Protocol ID", "Instrument ID"}));
       
        // then populate the JTable
        measurement.fillMeasurementJTable(jTable1);
    }//GEN-LAST:event_jButtonEditMeasurementActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextFieldMeasIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMeasIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMeasIDActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemMesocosmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMesocosmsActionPerformed
        // open the manage Rooms form
        ManageMesocosmsFormLONG mesocosmForm = new ManageMesocosmsFormLONG();
        mesocosmForm.setVisible(true);
        mesocosmForm.pack();
        mesocosmForm.setLocationRelativeTo(null);
        mesocosmForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemMesocosmsActionPerformed

    private void jMenuItemPublicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPublicationsActionPerformed
        // open the Discover SERENADE form
        ManagePublicationForm publicationForm = new ManagePublicationForm();
        publicationForm.setVisible(true);
        publicationForm.pack();
        publicationForm.setLocationRelativeTo(null);
        publicationForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemPublicationsActionPerformed

    private void jMenuItemInstitutionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInstitutionsActionPerformed
        // open the Institution form
        ManageInstitutionForm institutionForm = new ManageInstitutionForm();
        institutionForm.setVisible(true);
        institutionForm.pack();
        institutionForm.setLocationRelativeTo(null);
        institutionForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemInstitutionsActionPerformed

    private void jMenuItemBibliograpgyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBibliograpgyActionPerformed
        // open the bibliography form
        ManageBibliographyForm bibliograpgyForm = new ManageBibliographyForm();
        bibliograpgyForm.setVisible(true);
        bibliograpgyForm.pack();
        bibliograpgyForm.setLocationRelativeTo(null);
        bibliograpgyForm.setExtendedState(JFrame.MAXIMIZED_BOTH);
        bibliograpgyForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemBibliograpgyActionPerformed

    private void jMenuItemPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPeopleActionPerformed
        // open the Description form
        ManagePeopleForm peopleForm = new ManagePeopleForm();
        peopleForm.setVisible(true);
        peopleForm.pack();
        peopleForm.setLocationRelativeTo(null);
        peopleForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemPeopleActionPerformed

    private void jMenuItemProtocolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProtocolsActionPerformed
        // open the Manage protocol form
        ManageProtocolForm protocolForm = new ManageProtocolForm();
        protocolForm.setVisible(true);
        protocolForm.pack();
        protocolForm.setLocationRelativeTo(null);
        protocolForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemProtocolsActionPerformed

    private void jMenuItemInstrumentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInstrumentsActionPerformed
        // open the Manage Dictionary form
        ManageInstrumentForm instrumentForm = new ManageInstrumentForm();
        instrumentForm.setVisible(true);
        instrumentForm.pack();
        instrumentForm.setLocationRelativeTo(null);
        instrumentForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemInstrumentsActionPerformed

    private void jMenuItemMeasurementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMeasurementsActionPerformed
        // open the Institution form
        ManageMeasurementForm measurementForm = new ManageMeasurementForm();
        measurementForm.setVisible(true);
        measurementForm.pack();
        measurementForm.setLocationRelativeTo(null);
        measurementForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemMeasurementsActionPerformed

    private void jMenuItemDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDescriptionActionPerformed
        // open the Description form
        ManageDescriptionForm descriptionForm = new ManageDescriptionForm();
        descriptionForm.setVisible(true);
        descriptionForm.pack();
        descriptionForm.setLocationRelativeTo(null);
        descriptionForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemDescriptionActionPerformed

    private void jMenuItemDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDictionaryActionPerformed
        // open the Manage Dictionary form
        ManageDictionaryForm DictionaryForm = new ManageDictionaryForm();
        DictionaryForm.setVisible(true);
        DictionaryForm.pack();
        DictionaryForm.setLocationRelativeTo(null);
        DictionaryForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemDictionaryActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // open the Institution form
        SearchMesocosmsForm searchMesocosmForm = new SearchMesocosmsForm();
        searchMesocosmForm.setVisible(true);
        searchMesocosmForm.pack();
        searchMesocosmForm.setLocationRelativeTo(null);
        searchMesocosmForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
        // open the Institution form
        SearchMesocosmsForm searchMesocosmForm = new SearchMesocosmsForm();
        searchMesocosmForm.setVisible(true);
        searchMesocosmForm.pack();
        searchMesocosmForm.setLocationRelativeTo(null);
        searchMesocosmForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItemDiscoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDiscoverActionPerformed
        // open the Discover SERENADE form
        DiscoverSerenadeForm discoverSerenadeForm = new DiscoverSerenadeForm();
        discoverSerenadeForm.setVisible(true);
        discoverSerenadeForm.pack();
        discoverSerenadeForm.setLocationRelativeTo(null);
        discoverSerenadeForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemDiscoverActionPerformed

    private void jMenuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpActionPerformed
        // open the Help form
        HelpForm helpForm = new HelpForm();
        helpForm.setVisible(true);
        helpForm.pack();
        helpForm.setLocationRelativeTo(null);
        helpForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemHelpActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        // open the About form
        AboutForm aboutForm = new AboutForm();
        aboutForm.setVisible(true);
        aboutForm.pack();
        aboutForm.setLocationRelativeTo(null);
        aboutForm.setExtendedState(JFrame.MAXIMIZED_BOTH);
        aboutForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageMeasurementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageMeasurementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageMeasurementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageMeasurementForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageMeasurementForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAddMeasurement;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonClearMeasurement;
    private javax.swing.JButton jButtonEditMeasurement;
    private javax.swing.JButton jButtonRemoveMeasurement;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel60;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemBibliograpgy;
    private javax.swing.JMenuItem jMenuItemDescription;
    private javax.swing.JMenuItem jMenuItemDictionary;
    private javax.swing.JMenuItem jMenuItemDiscover;
    private javax.swing.JMenuItem jMenuItemHelp;
    private javax.swing.JMenuItem jMenuItemInstitutions;
    private javax.swing.JMenuItem jMenuItemInstruments;
    private javax.swing.JMenuItem jMenuItemMeasurements;
    private javax.swing.JMenuItem jMenuItemMesocosms;
    private javax.swing.JMenuItem jMenuItemPeople;
    private javax.swing.JMenuItem jMenuItemProtocols;
    private javax.swing.JMenuItem jMenuItemPublications;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDOI;
    private javax.swing.JTextField jTextFieldInherentID;
    private javax.swing.JTextField jTextFieldMeasID;
    private javax.swing.JTextField jTextFieldMeasType;
    private javax.swing.JTextField jTextFieldOwnerGroup;
    private javax.swing.JTextField jTextFieldParameter;
    private javax.swing.JTextField jTextFieldParameterDataType;
    private javax.swing.JTextField jTextFieldParameterDescription;
    private javax.swing.JTextField jTextFieldProtocolId;
    private javax.swing.JTextField jTextFieldReferencingID;
    private javax.swing.JTextField jTextFieldSourceDOI;
    private javax.swing.JTextField jTextFieldSourceID;
    private javax.swing.JTextField jTextFieldTimeAbsolute;
    private javax.swing.JTextField jTextFieldTimeRelative;
    private javax.swing.JTextField jTextFieldTimeUnit;
    private javax.swing.JTextField jTextFieldinstrumentId;
    private javax.swing.JTextField jTextFieldparameterNumeric;
    private javax.swing.JTextField jTextFieldparameterNumericOperator;
    private javax.swing.JTextField jTextFieldparameterStatistics;
    private javax.swing.JTextField jTextFieldparameterText;
    private javax.swing.JTextField jTextFieldparameterUncertaintyLow;
    private javax.swing.JTextField jTextFieldparameterUncertaintyType;
    private javax.swing.JTextField jTextFieldparameterUncertaintyUnit;
    private javax.swing.JTextField jTextFieldparameterUncertaintyUpper;
    private javax.swing.JTextField jTextFieldparameterUnit;
    // End of variables declaration//GEN-END:variables
}
