/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javaNanoSerenade;

import java.awt.Color;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import javax.swing.BorderFactory;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author aliay
 */
public class ManageDictionaryForm extends javax.swing.JFrame {

    
    DICTIONARY dictionary = new DICTIONARY();
    /**
     * Creates new form ManageRoomsForm
     */
    public ManageDictionaryForm() {
        initComponents();
        
        GraphicsDevice device = GraphicsEnvironment.getLocalGraphicsEnvironment().getDefaultScreenDevice();
 
                if( device.isFullScreenSupported() && !this.isDisplayable() ) {
                    this.setUndecorated(true);
                    device.setFullScreenWindow(this); 
                }else {
                    this.setExtendedState(JFrame.MAXIMIZED_BOTH);
                    this.setSize(Toolkit.getDefaultToolkit().getScreenSize());
                    this.setResizable(true); // on empêche de redimensionner la fenêtre 
                }
         //ajout d une icone serende pour la page
          this.setIconImage(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/lloogg_ser.png")).getImage());
        
         //populate the jtable
        dictionary.fillDictionaryJTable(jTable1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldGroup = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldParameter = new javax.swing.JTextField();
        jTextFieldItem = new javax.swing.JTextField();
        jTextFieldDictionaryID = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButtonBack = new javax.swing.JButton();
        jButtonClearDictionary = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButtonRemoveDictionary = new javax.swing.JButton();
        jButtonAddDictionary = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMesocosms = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPublications = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        jMenuItemInstitutions = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        jMenuItemBibliograpgy = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        jMenuItemPeople = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        jMenuItemProtocols = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        jMenuItemInstruments = new javax.swing.JMenuItem();
        jSeparator11 = new javax.swing.JPopupMenu.Separator();
        jMenuItemMeasurements = new javax.swing.JMenuItem();
        jSeparator12 = new javax.swing.JPopupMenu.Separator();
        jMenuItemDescription = new javax.swing.JMenuItem();
        jSeparator13 = new javax.swing.JPopupMenu.Separator();
        jMenuItemDictionary = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItemDiscover = new javax.swing.JMenuItem();
        jSeparator14 = new javax.swing.JPopupMenu.Separator();
        jMenuItemHelp = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAbout = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Manage Dictionary");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName(""); // NOI18N

        jPanel10.setBackground(new java.awt.Color(204, 204, 204));
        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Dictionary informations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 16))); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel9.setText("Group:");

        jTextFieldGroup.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGroupActionPerformed(evt);
            }
        });

        jLabel57.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel11.setText("Item:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel14.setText("Parameter:");

        jTextFieldParameter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jTextFieldItem.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldItemActionPerformed(evt);
            }
        });

        jTextFieldDictionaryID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextFieldDictionaryID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDictionaryIDActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 3, 14)); // NOI18N
        jLabel10.setText("Dictionary ID:");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel57)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1184, Short.MAX_VALUE)
                .addComponent(jLabel58)
                .addGap(45, 45, 45)
                .addComponent(jLabel52))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDictionaryID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldGroup, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addComponent(jTextFieldParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldDictionaryID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldGroup, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel52)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel57)
                    .addComponent(jLabel58)))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Dictionary ID", "Group", "Item", "Parameter"
            }
        )
        //make the jtable cell not editable
        {public boolean isCellEditable(int row, int column){return false;}}
    );
    jTable1.setGridColor(new java.awt.Color(204, 255, 0));

    jTable1.setSelectionBackground(new java.awt.Color(0, 153, 0));

    jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jTable1MouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(jTable1);

    jButtonBack.setBackground(new java.awt.Color(204, 204, 204));
    jButtonBack.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/back_button.png"))); // NOI18N
    jButtonBack.setToolTipText("Click to return to the main window.");
    jButtonBack.setBorderPainted(false);
    jButtonBack.setContentAreaFilled(false);
    jButtonBack.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonBack.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonBackActionPerformed(evt);
        }
    });

    jButtonClearDictionary.setBackground(new java.awt.Color(204, 204, 204));
    jButtonClearDictionary.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonClearDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/reset_button.png"))); // NOI18N
    jButtonClearDictionary.setToolTipText("Click to clear the fields.");
    jButtonClearDictionary.setBorderPainted(false);
    jButtonClearDictionary.setContentAreaFilled(false);
    jButtonClearDictionary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonClearDictionary.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonClearDictionaryActionPerformed(evt);
        }
    });

    jButton10.setBackground(new java.awt.Color(204, 204, 204));
    jButton10.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/edit_button.png"))); // NOI18N
    jButton10.setToolTipText("Click to edit the details of the selected dictionary.");
    jButton10.setBorderPainted(false);
    jButton10.setContentAreaFilled(false);
    jButton10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton10.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton10ActionPerformed(evt);
        }
    });

    jButtonRemoveDictionary.setBackground(new java.awt.Color(204, 204, 204));
    jButtonRemoveDictionary.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonRemoveDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/remove_button.png"))); // NOI18N
    jButtonRemoveDictionary.setToolTipText("Click to delete the selected dictionary.");
    jButtonRemoveDictionary.setBorderPainted(false);
    jButtonRemoveDictionary.setContentAreaFilled(false);
    jButtonRemoveDictionary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonRemoveDictionary.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonRemoveDictionaryActionPerformed(evt);
        }
    });

    jButtonAddDictionary.setBackground(new java.awt.Color(204, 204, 204));
    jButtonAddDictionary.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
    jButtonAddDictionary.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/save_button.png"))); // NOI18N
    jButtonAddDictionary.setToolTipText("Click to add a new dictionary.");
    jButtonAddDictionary.setBorderPainted(false);
    jButtonAddDictionary.setContentAreaFilled(false);
    jButtonAddDictionary.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButtonAddDictionary.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButtonAddDictionaryActionPerformed(evt);
        }
    });

    jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaNanoSerenade/image/exit_button.png"))); // NOI18N
    jButton1.setToolTipText("Click to close the application.");
    jButton1.setBorderPainted(false);
    jButton1.setContentAreaFilled(false);
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(61, 61, 61)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonAddDictionary, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(jButtonRemoveDictionary, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(jButtonClearDictionary, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(jButtonBack, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(75, 75, 75)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addContainerGap(40, Short.MAX_VALUE))
    );
    jPanel1Layout.setVerticalGroup(
        jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(11, 11, 11)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonBack, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonClearDictionary, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton10, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonRemoveDictionary)
                    .addComponent(jButtonAddDictionary))
                .addComponent(jButton1))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap(78, Short.MAX_VALUE))
    );

    jMenuBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    jMenuBar1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N

    jMenu5.setText("File ");

    jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_W, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem3.setText("Properties");
    jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem3ActionPerformed(evt);
        }
    });
    jMenu5.add(jMenuItem3);
    jMenu5.add(jSeparator4);

    jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem2.setText("Exit");
    jMenuItem2.setToolTipText("Click to close the application.");
    jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem2ActionPerformed(evt);
        }
    });
    jMenu5.add(jMenuItem2);

    jMenuBar1.add(jMenu5);

    jMenu1.setText("Edit >");
    jMenu1.add(jSeparator1);

    jMenuItemMesocosms.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemMesocosms.setText("Mesocosms");
    jMenuItemMesocosms.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemMesocosmsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemMesocosms);
    jMenu1.add(jSeparator2);

    jMenuItemPublications.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemPublications.setText("Publications");
    jMenuItemPublications.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemPublicationsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemPublications);
    jMenu1.add(jSeparator6);

    jMenuItemInstitutions.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemInstitutions.setText("Instutitions");
    jMenuItemInstitutions.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemInstitutionsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemInstitutions);
    jMenu1.add(jSeparator7);

    jMenuItemBibliograpgy.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemBibliograpgy.setText("Bibliograpgy");
    jMenuItemBibliograpgy.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemBibliograpgyActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemBibliograpgy);
    jMenu1.add(jSeparator8);

    jMenuItemPeople.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemPeople.setText("People");
    jMenuItemPeople.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemPeopleActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemPeople);
    jMenu1.add(jSeparator9);

    jMenuItemProtocols.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemProtocols.setText("Protocols");
    jMenuItemProtocols.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemProtocolsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemProtocols);
    jMenu1.add(jSeparator10);

    jMenuItemInstruments.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemInstruments.setText("Instruments");
    jMenuItemInstruments.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemInstrumentsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemInstruments);
    jMenu1.add(jSeparator11);

    jMenuItemMeasurements.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemMeasurements.setText("Measurements");
    jMenuItemMeasurements.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemMeasurementsActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemMeasurements);
    jMenu1.add(jSeparator12);

    jMenuItemDescription.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemDescription.setText("Description");
    jMenuItemDescription.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemDescriptionActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemDescription);
    jMenu1.add(jSeparator13);

    jMenuItemDictionary.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemDictionary.setText("Disctionary");
    jMenuItemDictionary.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemDictionaryActionPerformed(evt);
        }
    });
    jMenu1.add(jMenuItemDictionary);
    jMenu1.add(jSeparator3);

    jMenuBar1.add(jMenu1);

    jMenu3.setText("Search ");
    jMenu3.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenu3ActionPerformed(evt);
        }
    });

    jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItem4.setText("Query the database");
    jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItem4ActionPerformed(evt);
        }
    });
    jMenu3.add(jMenuItem4);

    jMenuBar1.add(jMenu3);

    jMenu2.setText("?");
    jMenu2.setToolTipText("More details about the SEREDATA ?");

    jMenuItemDiscover.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemDiscover.setText("Discover LabEX SERENADE");
    jMenuItemDiscover.setToolTipText("Know more about the SERENADE lab ?");
    jMenuItemDiscover.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemDiscoverActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItemDiscover);
    jMenu2.add(jSeparator14);

    jMenuItemHelp.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemHelp.setText("Help");
    jMenuItemHelp.setToolTipText("Need some help ? ");
    jMenuItemHelp.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemHelpActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItemHelp);
    jMenu2.add(jSeparator5);

    jMenuItemAbout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
    jMenuItemAbout.setText("About");
    jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jMenuItemAboutActionPerformed(evt);
        }
    });
    jMenu2.add(jMenuItemAbout);

    jMenuBar1.add(jMenu2);

    setJMenuBar(jMenuBar1);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGroupActionPerformed

    private void jTextFieldItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldItemActionPerformed

    private void jButtonAddDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddDictionaryActionPerformed
          //add a new cient
        
        //get data from the fields
        String group = jTextFieldGroup.getText();
        String item = jTextFieldItem.getText();
        String parameter = jTextFieldParameter.getText();
        
        
        if(group.trim().equals("") || item.trim().equals("") || parameter.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Required Fields -> Group + Item + Parameter.", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else {
            if(dictionary.addDictionary(group, item, parameter))
            {
                JOptionPane.showMessageDialog(rootPane, "New Dictionary added Successfully", "Add Dictionary", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(rootPane, "Dictionary Not Added ", "Add Dictionary Error", JOptionPane.ERROR_MESSAGE);
            }
        }
        //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"Dictionary ID", "Group", "Item", "Parameter"}));
       
        // then populate the JTable
        dictionary.fillDictionaryJTable(jTable1);
    }//GEN-LAST:event_jButtonAddDictionaryActionPerformed
 private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {                                     
        //display the selected row data in the jtextfields
        
        //get the jlabel model 
        DefaultTableModel model = (DefaultTableModel )jTable1.getModel();
                
        // get the selected row index
        int rIndex = jTable1.getSelectedRow();
        
        //display data 
        jTextFieldDictionaryID.setText(model.getValueAt(rIndex, 0).toString());
        jTextFieldGroup.setText(model.getValueAt(rIndex, 1).toString());
        jTextFieldItem.setText(model.getValueAt(rIndex, 2).toString());
        jTextFieldParameter.setText(model.getValueAt(rIndex, 3).toString());
    }                              
 
    private void jButtonClearDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearDictionaryActionPerformed
        // remove text from all jTextfields
        jTextFieldDictionaryID.setText("");
        jTextFieldGroup.setText("");
        jTextFieldItem.setText("");
        jTextFieldParameter.setText("");
        
    }//GEN-LAST:event_jButtonClearDictionaryActionPerformed

    private void jTextFieldDictionaryIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDictionaryIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDictionaryIDActionPerformed

    private void jButtonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackActionPerformed
        //clear the JTable first
       //jTable1.setModel(new DefaultTableModel(null, new Object[]{"Dictionary ID", "Group", "Item", "Parameter"}));
       this.toBack();
        setVisible(false);
        // then populate the JTable
        //dictionary.fillDictionaryJTable(jTable1);
    }//GEN-LAST:event_jButtonBackActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        //get data from the fields
        int dictionaryID = 0;
        String group = jTextFieldGroup.getText();
        String item = jTextFieldItem.getText();
        String parameter = jTextFieldParameter.getText();
        
          if(group.trim().equals("") || item.trim().equals("") || parameter.trim().equals(""))
        {
            JOptionPane.showMessageDialog(rootPane, "Required Fields -> Group + Item + Parameter.", "Empty Fields", JOptionPane.WARNING_MESSAGE);
        }
        else {
              
              try{
                    dictionaryID = Integer.valueOf(jTextFieldDictionaryID.getText());
                    
                    if(dictionary.editDictionary(dictionaryID, group, item, parameter))
                        {
                            JOptionPane.showMessageDialog(rootPane, "Dictionary Data Updated Successfully", "Edit Dictionary", JOptionPane.INFORMATION_MESSAGE);
                    }else{
                            JOptionPane.showMessageDialog(rootPane, "Dictionary Data Not Updated ", "Edit Dictionary Error", JOptionPane.ERROR_MESSAGE);
                        }
               }
              catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Dictionary Id ", "Dictionary ID Error", JOptionPane.ERROR_MESSAGE);
            }
                      
            
        }
          //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"Dictionary ID", "Group", "Item", "Parameter"}));
       
        // then populate the JTable
        dictionary.fillDictionaryJTable(jTable1);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButtonRemoveDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRemoveDictionaryActionPerformed
         // Delete the selected client
        try{
                    int dictionaryID = Integer.valueOf(jTextFieldDictionaryID.getText());
                    
                    if(dictionary.removeDictionary(dictionaryID))
                        {
                            JOptionPane.showMessageDialog(rootPane, "Dictionary Deleted Successfully", "Remove Dictionary", JOptionPane.INFORMATION_MESSAGE);
                    }
                    else{
                            JOptionPane.showMessageDialog(rootPane, "Dictionary Not Deleted ", "Remove Dictionary Error", JOptionPane.ERROR_MESSAGE);
                        }
               }
              catch(NumberFormatException ex)
              {
                JOptionPane.showMessageDialog(rootPane, ex.getMessage() + "Enter The Dictionary Id", "Dictionary ID Error", JOptionPane.ERROR_MESSAGE);
            }
        //clear the JTable first
       jTable1.setModel(new DefaultTableModel(null, new Object[]{"Dictionary ID", "Group", "Item", "Parameter"}));
       
        // then populate the JTable
        dictionary.fillDictionaryJTable(jTable1);
    }//GEN-LAST:event_jButtonRemoveDictionaryActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItemMesocosmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMesocosmsActionPerformed
        // open the manage Rooms form
        ManageMesocosmsFormLONG mesocosmForm = new ManageMesocosmsFormLONG();
        mesocosmForm.setVisible(true);
        mesocosmForm.pack();
        mesocosmForm.setLocationRelativeTo(null);
        mesocosmForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemMesocosmsActionPerformed

    private void jMenuItemPublicationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPublicationsActionPerformed
        // open the Discover SERENADE form
        ManagePublicationForm publicationForm = new ManagePublicationForm();
        publicationForm.setVisible(true);
        publicationForm.pack();
        publicationForm.setLocationRelativeTo(null);
        publicationForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemPublicationsActionPerformed

    private void jMenuItemInstitutionsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInstitutionsActionPerformed
        // open the Institution form
        ManageInstitutionForm institutionForm = new ManageInstitutionForm();
        institutionForm.setVisible(true);
        institutionForm.pack();
        institutionForm.setLocationRelativeTo(null);
        institutionForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemInstitutionsActionPerformed

    private void jMenuItemBibliograpgyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBibliograpgyActionPerformed
        // open the bibliography form
        ManageBibliographyForm bibliograpgyForm = new ManageBibliographyForm();
        bibliograpgyForm.setVisible(true);
        bibliograpgyForm.pack();
        bibliograpgyForm.setLocationRelativeTo(null);
        bibliograpgyForm.setExtendedState(JFrame.MAXIMIZED_BOTH);
        bibliograpgyForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemBibliograpgyActionPerformed

    private void jMenuItemPeopleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemPeopleActionPerformed
        // open the Description form
        ManagePeopleForm peopleForm = new ManagePeopleForm();
        peopleForm.setVisible(true);
        peopleForm.pack();
        peopleForm.setLocationRelativeTo(null);
        peopleForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemPeopleActionPerformed

    private void jMenuItemProtocolsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProtocolsActionPerformed
        // open the Manage protocol form
        ManageProtocolForm protocolForm = new ManageProtocolForm();
        protocolForm.setVisible(true);
        protocolForm.pack();
        protocolForm.setLocationRelativeTo(null);
        protocolForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemProtocolsActionPerformed

    private void jMenuItemInstrumentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInstrumentsActionPerformed
        // open the Manage Dictionary form
        ManageInstrumentForm instrumentForm = new ManageInstrumentForm();
        instrumentForm.setVisible(true);
        instrumentForm.pack();
        instrumentForm.setLocationRelativeTo(null);
        instrumentForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemInstrumentsActionPerformed

    private void jMenuItemMeasurementsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemMeasurementsActionPerformed
        // open the Institution form
        ManageMeasurementForm measurementForm = new ManageMeasurementForm();
        measurementForm.setVisible(true);
        measurementForm.pack();
        measurementForm.setLocationRelativeTo(null);
        measurementForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemMeasurementsActionPerformed

    private void jMenuItemDescriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDescriptionActionPerformed
        // open the Description form
        ManageDescriptionForm descriptionForm = new ManageDescriptionForm();
        descriptionForm.setVisible(true);
        descriptionForm.pack();
        descriptionForm.setLocationRelativeTo(null);
        descriptionForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemDescriptionActionPerformed

    private void jMenuItemDictionaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDictionaryActionPerformed
        // open the Manage Dictionary form
        ManageDictionaryForm DictionaryForm = new ManageDictionaryForm();
        DictionaryForm.setVisible(true);
        DictionaryForm.pack();
        DictionaryForm.setLocationRelativeTo(null);
        DictionaryForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemDictionaryActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // open the Institution form
        SearchMesocosmsForm searchMesocosmForm = new SearchMesocosmsForm();
        searchMesocosmForm.setVisible(true);
        searchMesocosmForm.pack();
        searchMesocosmForm.setLocationRelativeTo(null);
        searchMesocosmForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
        // open the Institution form
        SearchMesocosmsForm searchMesocosmForm = new SearchMesocosmsForm();
        searchMesocosmForm.setVisible(true);
        searchMesocosmForm.pack();
        searchMesocosmForm.setLocationRelativeTo(null);
        searchMesocosmForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItemDiscoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemDiscoverActionPerformed
        // open the Discover SERENADE form
        DiscoverSerenadeForm discoverSerenadeForm = new DiscoverSerenadeForm();
        discoverSerenadeForm.setVisible(true);
        discoverSerenadeForm.pack();
        discoverSerenadeForm.setLocationRelativeTo(null);
        discoverSerenadeForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemDiscoverActionPerformed

    private void jMenuItemHelpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemHelpActionPerformed
        // open the Help form
        HelpForm helpForm = new HelpForm();
        helpForm.setVisible(true);
        helpForm.pack();
        helpForm.setLocationRelativeTo(null);
        helpForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jMenuItemHelpActionPerformed

    private void jMenuItemAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAboutActionPerformed
        // open the About form
        AboutForm aboutForm = new AboutForm();
        aboutForm.setVisible(true);
        aboutForm.pack();
        aboutForm.setLocationRelativeTo(null);
        aboutForm.setExtendedState(JFrame.MAXIMIZED_BOTH);
        aboutForm.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

    }//GEN-LAST:event_jMenuItemAboutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageDictionaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageDictionaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageDictionaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageDictionaryForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageDictionaryForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButtonAddDictionary;
    private javax.swing.JButton jButtonBack;
    private javax.swing.JButton jButtonClearDictionary;
    private javax.swing.JButton jButtonRemoveDictionary;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemAbout;
    private javax.swing.JMenuItem jMenuItemBibliograpgy;
    private javax.swing.JMenuItem jMenuItemDescription;
    private javax.swing.JMenuItem jMenuItemDictionary;
    private javax.swing.JMenuItem jMenuItemDiscover;
    private javax.swing.JMenuItem jMenuItemHelp;
    private javax.swing.JMenuItem jMenuItemInstitutions;
    private javax.swing.JMenuItem jMenuItemInstruments;
    private javax.swing.JMenuItem jMenuItemMeasurements;
    private javax.swing.JMenuItem jMenuItemMesocosms;
    private javax.swing.JMenuItem jMenuItemPeople;
    private javax.swing.JMenuItem jMenuItemProtocols;
    private javax.swing.JMenuItem jMenuItemPublications;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator11;
    private javax.swing.JPopupMenu.Separator jSeparator12;
    private javax.swing.JPopupMenu.Separator jSeparator13;
    private javax.swing.JPopupMenu.Separator jSeparator14;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldDictionaryID;
    private javax.swing.JTextField jTextFieldGroup;
    private javax.swing.JTextField jTextFieldItem;
    private javax.swing.JTextField jTextFieldParameter;
    // End of variables declaration//GEN-END:variables
}
